<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-10T06:32:31Z" name="Default suite" finished-at="2021-01-10T06:32:54Z" duration-ms="23100">
    <groups>
    </groups>
    <test started-at="2021-01-10T06:32:31Z" name="Default test" finished-at="2021-01-10T06:32:54Z" duration-ms="23100">
      <class name="dummy.NewTest">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:dummy.NewTest@957e06]" started-at="2021-01-10T06:32:31Z" name="beforeTest" finished-at="2021-01-10T06:32:50Z" duration-ms="19169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="f()[pri:0, instance:dummy.NewTest@957e06]" started-at="2021-01-10T06:32:50Z" name="f" finished-at="2021-01-10T06:32:51Z" duration-ms="216" status="FAIL">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[unknown protocol: tel]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: unknown protocol: tel
at java.base/java.net.URL.<init>(URL.java:664)
at java.base/java.net.URL.<init>(URL.java:553)
at java.base/java.net.URL.<init>(URL.java:500)
at dummy.NewTest.f(NewTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:dummy.NewTest@957e06]" started-at="2021-01-10T06:32:51Z" name="afterTest" finished-at="2021-01-10T06:32:54Z" duration-ms="3638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- dummy.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
